q1

In [4]:
import gym
import numpy as np

# Create the OpenAI gym environment
env = gym.make('FrozenLake-v1')

# Initialize the Q-table with zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])

# Set hyperparameters
alpha = 0.8  # Learning rate
gamma = 0.95  # Discount factor
epsilon = 0.2  # Exploration rate
num_episodes = 5000  # Number of episodes to run

# Run the Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    done = False
    total_reward = 0

    while not done:
        # Choose an action using epsilon-greedy strategy
        if np.random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(Q[state, :])

        # Take the action and observe the next state and reward
        next_state, reward, done, _ = env.step(action)

        # Update the Q-table using the Q-learning formula
        Q[state, action] = (1 - alpha) * Q[state, action] + alpha * (reward + gamma * np.max(Q[next_state, :]))

        # Update the state and total reward
        state = next_state
        total_reward += reward

    # Print the total reward for this episode
    print(f"Episode {episode}: Total reward = {total_reward}")

# Print the final Q-table
print("Final Q-table:")
print(Q)


Streaming output truncated to the last 5000 lines.
Episode 17: Total reward = 0.0
Episode 18: Total reward = 0.0
Episode 19: Total reward = 0.0
Episode 20: Total reward = 0.0
Episode 21: Total reward = 0.0
Episode 22: Total reward = 0.0
Episode 23: Total reward = 0.0
Episode 24: Total reward = 0.0
Episode 25: Total reward = 0.0
Episode 26: Total reward = 0.0
Episode 27: Total reward = 0.0
Episode 28: Total reward = 0.0
Episode 29: Total reward = 0.0
Episode 30: Total reward = 0.0
Episode 31: Total reward = 0.0
Episode 32: Total reward = 0.0
Episode 33: Total reward = 0.0
Episode 34: Total reward = 0.0
Episode 35: Total reward = 0.0
Episode 36: Total reward = 0.0
Episode 37: Total reward = 0.0
Episode 38: Total reward = 0.0
Episode 39: Total reward = 0.0
Episode 40: Total reward = 0.0
Episode 41: Total reward = 0.0
Episode 42: Total reward = 0.0
Episode 43: Total reward = 0.0
Episode 44: Total reward = 0.0
Episode 45: Total reward = 0.0
Episode 46: Total reward = 0.0
Episode 47: Total r

q2

In [7]:
import gym

env = gym.make('Taxi-v3')
env.reset()

# Run the simulation for 100 steps
for t in range(100):
    # Choose a random action from the action space
    action = env.action_space.sample()

    # Take the chosen action and observe the next state, reward, and done flag
    state, reward, done, info = env.step(action)

    # Print out the results
    print("Action: ", action)
    print("State: ", state)
    print("Reward: ", reward)
    print("Done: ", done)

    # If the simulation has ended, reset the environment
    if done:
        env.reset()

# Close the environment when finished
env.close()


Action:  5
State:  363
Reward:  -10
Done:  False
Action:  5
State:  363
Reward:  -10
Done:  False
Action:  1
State:  263
Reward:  -1
Done:  False
Action:  3
State:  243
Reward:  -1
Done:  False
Action:  0
State:  343
Reward:  -1
Done:  False
Action:  0
State:  443
Reward:  -1
Done:  False
Action:  1
State:  343
Reward:  -1
Done:  False
Action:  5
State:  343
Reward:  -10
Done:  False
Action:  1
State:  243
Reward:  -1
Done:  False
Action:  5
State:  243
Reward:  -10
Done:  False
Action:  4
State:  243
Reward:  -10
Done:  False
Action:  1
State:  143
Reward:  -1
Done:  False
Action:  4
State:  143
Reward:  -10
Done:  False
Action:  1
State:  43
Reward:  -1
Done:  False
Action:  5
State:  43
Reward:  -10
Done:  False
Action:  3
State:  43
Reward:  -1
Done:  False
Action:  2
State:  63
Reward:  -1
Done:  False
Action:  3
State:  43
Reward:  -1
Done:  False
Action:  3
State:  43
Reward:  -1
Done:  False
Action:  2
State:  63
Reward:  -1
Done:  False
Action:  3
State:  43
Reward:  -1
Done: 

q3

In [15]:
import numpy as np

# Define the Q-value table
num_states = 10
num_actions = 4
Q = np.zeros((num_states, num_actions))

# Define the reinforcement learning parameters
alpha = 0.1
gamma = 0.9
epsilon = 0.1
num_episodes = 1000
max_steps_per_episode = 100

# Define the environment
def env_step(state, action):
    # Execute the action and observe the next state and reward
    if action == 0:
        next_state = max(0, state - 1)
    elif action == 1:
        next_state = min(num_states - 1, state + 1)
    elif action == 2:
        next_state = max(0, state - 2)
    else:
        next_state = min(num_states - 1, state + 2)
    reward = -1
    done = False
    if next_state == 0:
        reward = -100
        done = True
    elif next_state == num_states - 1:
        reward = 100
        done = True
    return next_state, reward, done

# Perform the reinforcement learning
for episode in range(num_episodes):
    # Reset the environment for the start of the episode
    state = np.random.randint(0, num_states)
    done = False

    for step in range(max_steps_per_episode):
        # Choose the next action using an epsilon-greedy policy
        if np.random.uniform() < epsilon:
            action = np.random.randint(0, num_actions)
        else:
            action = np.argmax(Q[int(state), :])

        # Execute the action and observe the next state and reward
        next_state, reward, done = env_step(state, action)

        # Update the Q-value table
        Q[int(state), action] += alpha * (reward + gamma * np.max(Q[int(next_state), :]) - Q[int(state), action])

        # Move to the next state
        state = next_state

        # End the episode if the terminal state is reached
        if done:
            print("Episode {} finished after {} timesteps with reward {}".format(episode + 1, step + 1, reward))
            break

    # Print the Q-value table at the end of the episode
    print("Q-value table after episode {}:".format(episode + 1))
    print(Q)


Streaming output truncated to the last 5000 lines.
 [ 8.70054042e+00  1.95550612e+02 -1.77000718e+01  1.12708734e+01]
 [ 9.41228352e+01  5.82582110e+01  3.74053893e+01  2.26014287e+02]
 [ 3.21267796e+01  2.13694511e+02  2.92548354e+01  2.40782156e+01]
 [ 1.15963059e+02  8.61951206e+01  1.05079951e+02  2.57790716e+02]
 [ 2.15062313e+02 -1.00000000e-01  3.19593141e+01  5.84770733e+01]
 [ 8.37136809e+01  1.40181073e+02  1.28510904e+02  2.91390539e+02]
 [ 4.11075711e+01  2.79112444e+02  3.93161120e+01  7.86472070e+01]
 [ 2.18489235e+02  2.76070367e+01  0.00000000e+00  5.16510980e+01]]
Episode 585 finished after 4 timesteps with reward 100
Q-value table after episode 585:
[[-1.84440231e+01 -1.06835192e-01 -1.64271863e+01  1.52309505e+02]
 [-5.29214457e+00  2.06985995e+01 -1.77123910e+01  1.85117085e+02]
 [ 8.70054042e+00  1.95550612e+02 -1.77000718e+01  1.12708734e+01]
 [ 9.41228352e+01  5.82582110e+01  3.74053893e+01  2.26514023e+02]
 [ 3.21267796e+01  2.13694511e+02  2.92548354e+01  2.407