In [26]:
import numpy as np

In [27]:
data=np.random.rand(2,3,4) #  x y z
zeros=np.zeros((2,2,2))
full=np.full((2,2,2),7)
ones=np.ones((2,2,2))

In [28]:
print(data)

[[[0.22611906 0.340451   0.62859971 0.47315313]
  [0.40293623 0.42255045 0.69406764 0.9900187 ]
  [0.46086838 0.48731473 0.57165599 0.37958446]]

 [[0.02529236 0.25226578 0.77530968 0.01118228]
  [0.29229026 0.94828714 0.53851451 0.1499894 ]
  [0.42595549 0.48447989 0.75203819 0.34360671]]]


In [29]:
print(zeros)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [30]:
print(full)

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


In [31]:
print(ones)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [32]:
arr=np.array([
    [1,2,3,4],
    [1,2,3,4]
])

In [33]:
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [1 2 3 4]]


In [34]:
# attributes
shape=data.shape
size=data.size
types=data.dtype

In [35]:
print("shape: ",shape)
print("size: ",size)
print("types: ",types)

shape:  (2, 3, 4)
size:  24
types:  float64


In [36]:
# slicing
arr=data[0]
slicer=data[0:2]
reverse=data[-1]

In [37]:
print('arr: ',arr)
print('slicer: ',slicer)
print('reverse: ',reverse)


arr:  [[0.22611906 0.340451   0.62859971 0.47315313]
 [0.40293623 0.42255045 0.69406764 0.9900187 ]
 [0.46086838 0.48731473 0.57165599 0.37958446]]
slicer:  [[[0.22611906 0.340451   0.62859971 0.47315313]
  [0.40293623 0.42255045 0.69406764 0.9900187 ]
  [0.46086838 0.48731473 0.57165599 0.37958446]]

 [[0.02529236 0.25226578 0.77530968 0.01118228]
  [0.29229026 0.94828714 0.53851451 0.1499894 ]
  [0.42595549 0.48447989 0.75203819 0.34360671]]]
reverse:  [[0.02529236 0.25226578 0.77530968 0.01118228]
 [0.29229026 0.94828714 0.53851451 0.1499894 ]
 [0.42595549 0.48447989 0.75203819 0.34360671]]


In [40]:
list1=np.random.random(10)
list2=np.random.random(10)

In [39]:
print(list1)

[0.1130348  0.82364627 0.46244181 0.93167074 0.55418472 0.45800321
 0.39672404 0.30866922 0.5699079  0.07980207]


In [41]:
print(list2)

[0.64985554 0.22412536 0.43477264 0.67065666 0.01438918 0.88990937
 0.51429326 0.43107856 0.93553821 0.97277282]


In [46]:
add=np.add(list1,list2)
sub=np.subtract(list1,list2)
div=np.divide(list1,list2)
mul=np.multiply(list1,list2)
dot=np.dot(list1,list2)


In [45]:
print(add)
print(sub)
print(div)
print(mul)
print(dot)


[0.78751611 0.36273476 0.68391633 0.87527513 0.12727529 1.50678386
 0.88160813 0.44284131 0.99760555 1.02651231]
[-0.51219497 -0.08551595 -0.18562894 -0.46603819  0.09849692 -0.27303488
 -0.14697839 -0.4193158  -0.87347087 -0.91903333]
[0.21183257 0.61844587 0.57304363 0.30510167 7.84520621 0.693188
 0.71421288 0.0272868  0.06634399 0.05524362]
[0.08945949 0.03106588 0.10832086 0.13722874 0.00162434 0.54896239
 0.18890756 0.00507067 0.05806637 0.05227631]
1.22098260877389


In [47]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [49]:
data[0][0][0]=100

In [50]:
print(data.shape)

(2, 3, 4)


In [57]:
data=data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [63]:
# delete

np.delete(data,0,axis=0)

array([[[0.02529236, 0.25226578, 0.77530968, 0.01118228, 0.29229026,
         0.94828714],
        [0.53851451, 0.1499894 , 0.42595549, 0.48447989, 0.75203819,
         0.34360671]]])

In [64]:
np.save('newArr',data)

In [68]:
test=np.load('newArr.npy')
print(test)

[[[1.00000000e+02 3.40451000e-01 6.28599713e-01 4.73153126e-01
   4.02936225e-01 4.22550448e-01]
  [6.94067644e-01 9.90018700e-01 4.60868385e-01 4.87314730e-01
   5.71655986e-01 3.79584455e-01]]

 [[2.52923551e-02 2.52265782e-01 7.75309681e-01 1.11822772e-02
   2.92290260e-01 9.48287140e-01]
  [5.38514507e-01 1.49989400e-01 4.25955491e-01 4.84479893e-01
   7.52038191e-01 3.43606706e-01]]]
