In [1]:
data = []
print('Tell me about yourself')
while True:
    line =input() 
    if line:
        data.append(line)
    else:
        break
    finalText ='\n'.join(data)
    print('\n')

Tell me about yourself




































In [8]:
var1 = 'hello world'
var2 = 'python'
print(var1[4:0])

In [26]:
import pandas as pd
dataFrame=pd.read_csv("student.csv",header=None)
print(dataFrame)

          0  1
0  sharjeel  1
1     ahmed  2
2       ali  3
3    shazim  4


In [27]:
print(dataFrame.loc[0])

0    sharjeel
1           1
Name: 0, dtype: object


In [28]:
print(dataFrame.loc[[0,1]])

          0  1
0  sharjeel  1
1     ahmed  2


In [51]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)

print(df) 

   calories  duration
0       420        50
1       380        40
2       390        45


In [52]:
df['calories+duration']=(df['calories']+df['duration'])

In [53]:
print(df)

   calories  duration  calories+duration
0       420        50                470
1       380        40                420
2       390        45                435


In [54]:
df.drop(columns=['calories','duration'],inplace=True)

In [56]:
print(df)

   calories+duration
0                470
1                420
2                435


In [58]:
df.append({'calories+duration':35},ignore_index=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_5636\281661509.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append({'calories+duration':35},ignore_index=True)


calories+duration
0                470
1                420
2                435
3                 35

In [60]:
temp = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

In [61]:
df2=pd.DataFrame(temp)

In [63]:
df= df.append(df2,ignore_index=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_5636\1685602066.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df= df.append(df2,ignore_index=True)


In [64]:
print(df)

   calories+duration  calories  duration
0              470.0       NaN       NaN
1              420.0       NaN       NaN
2              435.0       NaN       NaN
3                NaN     420.0      50.0
4                NaN     380.0      40.0
5                NaN     390.0      45.0


In [66]:
df.drop(index=4,inplace=True)

In [80]:
import numpy as np
df.drop(index=df[df['duration']==50.0 ].index,inplace=True)

In [81]:
print(df)

   calories+duration  calories  duration
0              470.0       NaN       NaN
1              420.0       NaN       NaN
2              435.0       NaN       NaN
5                NaN     390.0      45.0


In [85]:
#Slicing arrays:
#Slicing in python means taking elements from one given index to another given index.
#We pass slice instead of index like this: [start:end].
#We can also define the step, like this: [start:end:step]
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
#Slice elements from index 1 to index 5 from the following array:
print(arr[1:5])

#Slice elements from index 4 to the end of the array:
print(arr[4:])
#Slice elements from the beginning to index 4 (not included):
print(arr[:4])
#Negative Slicing:
#Slice from the index 3 from the end to index 1 from the end:
print(arr[-3:-1])
#STEP
#Use the step value to determine the step of the slicing:
#Return every other element from index 1 to index 5:
print("-----------------------")
print(arr[1:5:2])
#Return every other element from the entire array:
print(arr[::2])
#Slicing 2-D Arrays
#From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
#From both elements, return index 2:
print(arr[0:2, 2])
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2, 1:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
-----------------------
[2 4]
[1 3 5 7]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [87]:
#Removing stop words with NLTK in Python
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
print(stopwords.words('english'))
#The following program removes stop words from a piece of text:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
example_sent = """This is a sample sentence,
showing off the stop words filtration."""
stop_words = set(stopwords.words('english'))
word_tokens = word_tokenize(example_sent)
# converts the words in word_tokens to lower case and then checks whether
#they are present in stop_words or not
filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]
#with no lower case conversion
filtered_sentence = []
for w in word_tokens:
    if w not in stop_words:
        filtered_sentence.append(w)
        print(word_tokens)
        print(filtered_sentence)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...


['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

[nltk_data]   Unzipping corpora\stopwords.zip.
